---
title: "p8105_final_project_proposal"
author: "All group members"
date: "2022-11-10"
output: github_document
---


## The group members (names and UNIs):
- Wenjun Mo (wm2473)
- Keming Zhan (kz2383)
- Pei Liu (pl2848)
- Shuting Kang (sk5152)

## The tentative project title
**Children Care vs. Violation in NYC**
 
## The motivation for this project
- To investigate the violation in each Children Center in NYC.

## The intended final products
- A webpage with index page, statistical analysis, visualization, report etc.
- A screencast that introduce our project
- A clean data including the center name, zip code, average violation rate, average total educational workers
- A map represent violation rate in each borough in NYC
Several plotly plots that display average critical violation rate interactively based on geographic factor and children centers

## The anticipated data sources
**NYC Open Data**
https://data.cityofnewyork.us/Health/DOHMH-Childcare-Center-Inspections/dsg6-ifza


## The planned analyses / visualizations / coding challenges
- filter the variables to include currently permitted Children Care Center
- Visualize the relationship between each indicator and violation measure. 
Coding Challenge: 
- Explanatory data analysis, generate a more lucid version through classifying based on multiple factors, for instance geographic factor and children center 
- Define the categorical and numerical variable (unique value in each variable)

## The planned timeline
11.15 - 11.18: project review meeting 
11.18 - 11.30: Statistical analysis, EDA and visulazation
12.1 - 12.5: website
12.5 - 12.10: screencast
12.10: final report,webpage and screencast 
12.10 final report deadline (webpage&screen cast)

